version: '2'

services:
  nginx:
    build: './docks/nginx/.'
    ports:
      - '8080:80'
    volumes_from:
      - web:ro
    depends_on:
      - web

  web:
    build: './sources/.'
    image: 'websource'
    ports:
      - '127.0.0.1:8000:8000'
    env_file: '.env'
    command: 'gunicorn _project_.wsgi:application -w 2 -b :8000 --capture-output --enable-stdio-inheritance --log-level=debug --access-logfile=- --log-file=-'
    volumes:
      - 'cachedata:/cache'
      - 'mediadata:/media'
    depends_on:
      - postgres
      - redis
      - mongo

  realtime:
    image: 'websource'
    ports:
      - '127.0.0.1:9999:9999'
    env_file: '.env'
    command: 'python realtime_ws_server.py'
    volumes_from:
      - web
    depends_on:
      - web

  celery_worker:
    image: 'websource'
    env_file: '.env'
    command: 'python -m celery -A _project_ worker -l debug'
    volumes_from:
      - web
    depends_on:
      - web

  celery_beat:
    container_name: 'celery_beat'
    image: 'websource'
    env_file: '.env'
    command: 'python -m celery -A _project_ beat --pidfile= -l debug'
    volumes_from:
      - web
    depends_on:
      - web

  postgres:
    container_name: 'postgres'
    image: 'postgres:9.5.3'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'

  mongo:
    container_name: 'mongo'
    image: 'mongo:3.3'
    command: '--storageEngine wiredTiger'
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - 'mongodata:/data/db'

volumes:
  pgdata:
  redisdata:
  cachedata:
  mediadata:
  mongodata:
