version: '2'
services:
  revp:
    image: nginx:latest
    volumes:
      - "/root/projects/private-registry/:/usr/share/nginx/html:ro"
      - "/root/projects/private-registry/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/root/projects/private-registry/certs:/usr/share/certs:ro"
      - "/root/projects/private-registry/auth/htpasswd:/etc/nginx/.htpasswd:ro"
    ports:
#      - "80:80"
      - "443:443"
    depends_on:
      - reg
    links:
      - reg
  reg:
    image: registry
    expose:
      - 5000
    volumes:
      - "/root/projects/private-registry/reg-data:/var/lib/registry:rw"
